# Changes here will be overwritten by Copier
_commit: v3.3.0
_src_path: https://github.com/stkr22/copier-python-project.git
author_email: stkr22@github.com
author_full_name: stkr22
codeowner_username: '@stkr22'
copyright_license: GPL-3.0
github_repository_name: private-assistant-curtain-skill-py
github_username: stkr22
project_description: 'Curtain Control Skill for Private Assistant: Enables automated
    and voice-activated curtain control within smart home environments.'
project_name: Private Assistant Curtain Skill
publish_to_pypi: false
python_package_distribution_name: private-assistant-curtain-skill
python_package_import_name: private_assistant_curtain_skill
python_package_version: 1.1.1
use_containers: true
